project:
  type: website
  output-dir: docs
  
website:
  title: "PartidismoMinisterialAL"
  navbar:
    left:
      - href: index.qmd
        text: Sobre el proyecto
      - href: integrantes.qmd
        text: Integrantes
        
    right:
      - icon: github
        href: https://github.com/anabellanilom/PartidismoMinisterialAL 
      - icon: envelope
        href: mailto:anabella.anilom@gmail.com
      
  page-footer:
    left: "Â© 2025 Anabella Molina. Contenido bajo licencia <a href='https://creativecommons.org/licenses/by-nc/4.0/'>CC BY-NC 4.0</a>"
    center: "Hecho con [Quarto](https://quarto.org)"
    right: "Alojado en [GitHub Pages](https://pages.github.com)"
   
format:
  html:
    css: styles.css
    theme: cosmo
    toc: true
